version: "3.8"

services:
  # Drupal Service
  drupal:
    image: drupal:latest
    depends_on:
      - mariadb
    ports:
      - "8081:80"
    environment:
      DRUPAL_DATABASE_HOST: mariadb
      DRUPAL_DATABASE_NAME: your_drupal_database
      DRUPAL_DATABASE_USER: your_drupal_user
      DRUPAL_DATABASE_PASSWORD: your_drupal_password
    volumes:
      - ./drupal:/var/www/html/

# Networks
networks:
  mynetwork:
