version: "3.8"
services:

  # PHP Service
  php:
    build: './php_docker/'
    volumes:
      - ./www/:/var/www/html/

  # Apache Service
  apache:
    build: './apache_docker/'
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./www/:/var/www/html/

  # MariaDB Service
  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
    env_file:
      - .secrets.env

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb

  # Drupal Service
  drupal:
    image: drupal:latest
    depends_on:
      - mariadb
    ports:
      - "8081:80"
    environment:
      DRUPAL_DATABASE_HOST: ${DRUPAL_DATABASE_HOST}
      DRUPAL_DATABASE_NAME: ${DRUPAL_DATABASE_NAME}
      DRUPAL_DATABASE_USER: ${DRUPAL_DATABASE_USER}
      DRUPAL_DATABASE_PASSWORD: ${DRUPAL_DATABASE_PASSWORD}
    volumes:
      - ./drupal:/var/www/html/
    env_file:
      - .secrets.env

# Volumes
volumes:
  mysqldata:

