version: '3'

services:
  ldap:
    image: bitnami/openldap:latest
    container_name: openldap
    environment:
      - LDAP_ORGANISATION=My Organization
      - LDAP_DOMAIN=mangoflame.com
      - LDAP_ADMIN_PASSWORD=Linux4Ever
      - LDAP_ROOT_PASSWORD=Linux4Ever
      - ALLOW_EMPTY_PASSWORD=yes
      
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./ldap-init:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - ./ldap-data:/bitnami/openldap
